//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLogiscool.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyLogiscoolDatabaseEntities : DbContext
    {
        public MyLogiscoolDatabaseEntities()
            : base("name=MyLogiscoolDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<OwnerSchoolConnector> OwnerSchoolConnector { get; set; }
        public virtual DbSet<Schools> Schools { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
