//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLogiscool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerSchoolConnector
    {
        public int Connection_Id { get; set; }
        public int Owner_Id { get; set; }
        public int School_Id { get; set; }
    
        public virtual Owners Owners { get; set; }
        public virtual Schools Schools { get; set; }
    }
}
