//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLogiscool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owners()
        {
            this.OwnerSchoolConnector = new HashSet<OwnerSchoolConnector>();
        }
    
        public int Owner_Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<bool> HasPaidThisYear { get; set; }
        public Nullable<bool> IsReplaceable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OwnerSchoolConnector> OwnerSchoolConnector { get; set; }
    }
}
