//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLogiscool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int Teacher_Id { get; set; }
        public int School_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<bool> WellLiked { get; set; }
        public Nullable<int> CourseNumber { get; set; }
        public string HealthCare { get; set; }
    
        public virtual Schools Schools { get; set; }
    }
}
